image: rabits/qt:5.9-desktop

variables:
  http_proxy: "http://10.144.1.10:8080/"

before_script:
  - echo $http_proxy
  - curl https://www.zlib.net/zlib-1.2.11.tar.gz

build:
  script:
    - ls -l
    - make