image: rabits/qt:5.9-desktop

variables:
  http_proxy: "http://10.144.1.10:8080/"
  https_proxy: "https://10.144.1.10:8080/"

before_script:
  - curl -o zlib-1.2.11.tar.gz https://www.zlib.net/zlib-1.2.11.tar.gz
  - tar -zxf zlib-1.2.11.tar.gz
  - cd zlib-1.2.11 && ./configure && make && make install

build:
  script:
    - make