variables:
  QT_BIN: /data/s/kerwu/Qt5.9.4/5.9.4/gcc_64/bin
  QT_IFW_BIN: /data/s/kerwu/QtIFW-3.1.1/bin

stages:
  - deploy

before_script:
  - PATH=$QT_BIN:$QT_IFW_BIN:$PATH

linux-deploy:
  stage: deploy
  only:
    - tags
  script:
    - python VisualStatistics/installer.py prebuild
    - cd build-VisualStatistics-Release
    - qmake ../VisualStatistics/VisualStatistics.pro DEFINES+=INSTALLER
    - make && cd ..
    - python VisualStatistics/installer.py postbuild
  cache:
    paths:
      - installer/installer/packages/crashreporter/data/
      - installer/installer/packages/dlls/data/
      - installer/installer/packages/visualstatistics/data/VisualStatistics.sh
      - installer/installer/packages/visualstatistics/data/VisualStatistics.png
