name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-12
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.9.4'
          target: 'desktop'
          arch: 'clang_64'
          cache: true

      - name: Build QScintilla
        run: |
          wget https://www.riverbankcomputing.com/static/Downloads/QScintilla/2.11.6/QScintilla-2.11.6.zip
          unzip QScintilla-2.11.6.zip
          cd QScintilla-2.11.6/Qt4Qt5
          qmake CONFIG+=staticlib
          make
          make install

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build libexpat
        run: |
          cd VisualStatistics/libexpat/expat
          ./buildconf.sh
          ./configure
          make