name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-12
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.9.4'
          target: 'desktop'
          arch: 'clang_64'
          cache: true

      - name: Install automake
        run: brew install automake

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build libexpat
        run: |
          cd VisualStatistics/libexpat/expat
          ./buildconf.sh
          ./configure
          make

      - name: Build pcre2
        run: |
          cd VisualStatistics/pcre2
          ./autogen.sh
          ./configure
          make

      - name: Build QuaZIP
        run: |
          mkdir build-quazip-Release
          cd build-quazip-Release
          qmake LIBS+=-lz ../VisualStatistics/quazip/quazip/quazip.pro
          make

      - name: Cache QScintilla
        id: cache-qsci
        uses: actions/cache@v3
        with:
          path: |
            $Qt5_DIR/lib/libqscintilla2_qt5.a
            $Qt5_DIR/include/Qsci
            $Qt5_DIR/translations
            $Qt5_DIR/qsci
            $Qt5_DIR/mkspecs/features/qscintilla2.prf
          key: QScintillaCache

      - name: Build QScintilla
        if: steps.cache-qsci.outputs.cache-hit != 'true'
        run: |
          wget https://www.riverbankcomputing.com/static/Downloads/QScintilla/2.11.6/QScintilla-2.11.6.zip
          unzip QScintilla-2.11.6.zip
          cd QScintilla-2.11.6/Qt4Qt5
          qmake CONFIG+=staticlib
          make
          make install

      - name: Build Visual Statistics
        run: |
          qmake DEFINES+=DEPLOY_VISUALSTAT VisualStatistics/VisualStatistics.pro
          make qmake_all
          make
